# Generated by Django 4.1.13 on 2026-03-22 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(default='bogota', max_length=50)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_blog', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(blank=True, max_length=500, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.CharField(blank=True, choices=[('CUIDADO', 'Cuidado'), ('ENTRENAMIENTO', 'Entrenamiento'), ('SALUD', 'Salud'), ('HISTORIAS', 'Historias'), ('CONSEJOS', 'Consejos')], max_length=20, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('visitas', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('edad_aproximada', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('tamano', models.CharField(max_length=20)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado_salud', models.TextField(blank=True, null=True)),
                ('vacunado', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('microchip', models.BooleanField(default=False)),
                ('estado_adopcion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada'), ('disponible', 'Disponible'), ('en_proceso', 'En Proceso')], default='disponible', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(blank=True, max_length=500, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.CharField(blank=True, choices=[('ADOPCION', 'Adopción'), ('CUIDADO', 'Cuidado'), ('EVENTOS', 'Eventos'), ('SALUD', 'Salud'), ('GENERAL', 'General')], max_length=20, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'noticias',
            },
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id_refugio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_refugio', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refugios',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateField()),
                ('tipo_seguimiento', models.CharField(choices=[('LLAMADA', 'Llamada'), ('VISITA', 'Visita'), ('REPORTE_ADOPTANTE', 'Reporte Adoptante'), ('VETERINARIO', 'Veterinario')], max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_mascota', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('PREOCUPANTE', 'Preocupante')], default='BUENO', max_length=20)),
                ('proximo_seguimiento', models.DateField(blank=True, null=True)),
                ('realizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.mascota')),
            ],
            options={
                'db_table': 'seguimientos',
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='refugio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='core.refugio'),
        ),
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.mascota')),
            ],
            options={
                'db_table': 'galeria_fotos',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contenido', models.CharField(max_length=20)),
                ('comentario', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.blog')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_adopcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('estado_adopcion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada'), ('disponible', 'Disponible'), ('en_proceso', 'En Proceso')], default='pendiente', max_length=20)),
                ('url_formulario_descarga', models.CharField(blank=True, max_length=500, null=True)),
                ('formulario_enviado', models.BooleanField(default=False)),
                ('fecha_envio_formulario', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='core.mascota')),
            ],
            options={
                'db_table': 'adopciones',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios_app', to='core.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
