# Generated by Django 4.1.13 on 2026-03-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='galeriafoto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto principal'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='refugio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='refugios/', verbose_name='Foto del refugio'),
        ),
        migrations.AlterField(
            model_name='galeriafoto',
            name='url_foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
