# Generated by Django 6.0.3 on 2026-03-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refugios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('raza', models.CharField(blank=True, max_length=255, null=True)),
                ('edad_aproximada', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=255)),
                ('tamano', models.CharField(max_length=255)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado_salud', models.TextField(blank=True, null=True)),
                ('vacunado', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('microchip', models.BooleanField(default=False)),
                ('estado_adopcion', models.CharField(choices=[('disponible', 'Disponible'), ('pendiente', 'Pendiente'), ('adoptado', 'Adoptado')], default='disponible', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fcha_registro', models.DateTimeField(auto_now_add=True)),
                ('refugio', models.ForeignKey(blank=True, db_column='id_refugio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='refugios.refugio')),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
    ]
