# Generated by Django 6.0.3 on 2026-03-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id_foto', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_foto', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mascotas.mascota')),
            ],
            options={
                'db_table': 'galeria_fotos',
            },
        ),
    ]
