# Generated by Django 6.0.3 on 2026-03-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_galeriafoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='fcha_registro',
            new_name='fecha_registro',
        ),
    ]
