# Generated by Django 6.0.3 on 2026-03-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_rename_fcha_registro_mascota_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas_fotos/'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
