# Generated by Django 6.0.6 on 2026-06-27 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_mascota_foto_alter_mascota_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
