# Generated by Django 6.0.6 on 2026-07-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_mascota_foto_alter_mascota_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
