# Generated by Django 6.0.6 on 2026-07-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascota_foto'),
        ('mascotas', '0005_mascota_activo'),
    ]

    operations = [
    ]
