# Generated by Django 6.0.6 on 2026-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_merge_0005_alter_mascota_foto_0005_mascota_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas_fotos/'),
        ),
    ]
