# Generated by Django 6.0.3 on 2026-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id_refugio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomrefugio', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refugios',
            },
        ),
    ]
