# Generated by Django 6.0.3 on 2026-03-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refugio',
            old_name='nomrefugio',
            new_name='nombre_refugio',
        ),
    ]
