# Generated by Django 6.0.3 on 2026-03-29 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0002_rename_nomrefugio_refugio_nombre_refugio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='usuario_encargado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mi_refugio', to=settings.AUTH_USER_MODEL),
        ),
    ]
