# Generated by Django 6.0.6 on 2026-07-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0003_refugio_usuario_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='especialidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='recibe_animales',
            field=models.BooleanField(default=True),
        ),
    ]
