# Generated by Django 6.0.6 on 2026-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0004_refugio_especialidad_refugio_recibe_animales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugio',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='refugio',
            name='recibe_animales',
        ),
        migrations.AlterField(
            model_name='refugio',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
