# Generated by Django 6.0.6 on 2026-07-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0005_remove_refugio_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='localidad',
            field=models.CharField(choices=[('usaquen', 'Usaquén'), ('chapinero', 'Chapinero'), ('santa_fe', 'Santa Fe'), ('san_cristobal', 'San Cristóbal'), ('usme', 'Usme'), ('tunjuelito', 'Tunjuelito'), ('bosa', 'Bosa'), ('kennedy', 'Kennedy'), ('fontibon', 'Fontibón'), ('engativa', 'Engativá'), ('suba', 'Suba'), ('barrios_unidos', 'Barrios Unidos'), ('teusaquillo', 'Teusaquillo'), ('los_martires', 'Los Mártires'), ('antonio_narino', 'Antonio Nariño'), ('puente_aranda', 'Puente Aranda'), ('la_candelaria', 'La Candelaria'), ('rafael_uribe', 'Rafael Uribe Uribe'), ('ciudad_bolivar', 'Ciudad Bolívar'), ('sumapaz', 'Sumapaz')], default='usme', max_length=50),
            preserve_default=False,
        ),
    ]
