# Generated by Django 6.0.6 on 2026-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0006_alter_refugio_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='localidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
