# Generated by Django 6.0.3 on 2026-03-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_blog', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.CharField(blank=True, choices=[('CUIDADO', 'Cuidado'), ('ENTRENAMIENTO', 'Entrenamiento'), ('SALUD', 'Salud'), ('HISTORIAS', 'Historias'), ('CONSEJOS', 'Consejos')], max_length=50, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('visitas', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.CharField(blank=True, choices=[('ADOPCION', 'Adopción'), ('CUIDADO', 'Cuidado'), ('EVENTOS', 'Eventos'), ('SALUD', 'Salud'), ('GENERAL', 'General')], max_length=50, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'noticias',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_contenido', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, db_column='id_blog', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('noticia', models.ForeignKey(blank=True, db_column='id_noticia', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.noticia')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
    ]
