# Generated by Django 6.0.3 on 2026-03-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_adopcion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('estado_adopcion', models.CharField(choices=[('disponible', 'Disponible'), ('pendiente', 'Pendiente'), ('adoptado', 'Adoptado')], default='pendiente', max_length=20)),
                ('url_formulario_descarga', models.CharField(blank=True, max_length=255, null=True)),
                ('formulario_enviado', models.BooleanField(default=False)),
                ('fecha_envio_formulario', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fcha_registro', models.DateTimeField(auto_now_add=True)),
                ('adoptante', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
            options={
                'db_table': 'adopciones',
            },
        ),
    ]
