# Generated by Django 6.0.3 on 2026-03-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
        ('mascotas', '0002_galeriafoto'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateField()),
                ('tipo_seguimiento', models.CharField(choices=[('LLAMADA', 'Llamada'), ('VISITA', 'Visita'), ('REPORTE_ADOPTANTE', 'Reporte Adoptante'), ('VETERINARIO', 'Veterinario')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_mascota', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN_TRATAMIENTO', 'En Tratamiento')], default='BUENO', max_length=50)),
                ('proximo_seguimiento', models.DateField(blank=True, null=True)),
                ('realizado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('adoptante', models.ForeignKey(db_column='id_adoptante', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
            options={
                'db_table': 'seguimientos',
            },
        ),
    ]
