# Generated by Django 6.0.4 on 2026-04-11 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='adoptante',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='estado_mascota',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='fecha_seguimiento',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='id_seguimiento',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='proximo_seguimiento',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='tipo_seguimiento',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='adopcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='adopciones.adopcion'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='estado_bienestar',
            field=models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular (Requiere atención)'), ('critico', 'Crítico / Peligro')], default='bueno', max_length=20),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='fecha_contacto',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='proxima_fecha',
            field=models.DateField(blank=True, help_text='¿Cuándo se debe volver a contactar?', null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='tipo_contacto',
            field=models.CharField(choices=[('visita', 'Visita Presencial'), ('llamada', 'Llamada Telefónica'), ('whatsapp', 'Mensaje / WhatsApp'), ('correo', 'Correo Electrónico')], default='llamada', max_length=20),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Detalles de la adaptación, comportamiento, etc.', null=True),
        ),
        migrations.AlterModelTable(
            name='seguimiento',
            table=None,
        ),
    ]
