# Generated by Django 5.1 on 2026-05-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_remove_seguimiento_adoptante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
