# Generated by Django 5.1 on 2026-05-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0004_alter_seguimiento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
