# Generated by Django 6.0.6 on 2026-07-04 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_activo_rename_activo_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id_actividad', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
